services:
  elastic-itshopper:
    image: elastic-itshopper:latest
    mem_reservation: 1GB
    ports:
      - 9200:9200
    networks:
      - elk-network
  logstash-itshopper:
    image: logstash-itshopper:latest
    ports:
      - 5044:5044
      - 5069:5069/udp
    networks:
      - elk-network
  kibana-itshopper:
    image: kibana-itshopper:latest
    ports:
      - 5601:5601
    networks:
      - elk-network
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres-itshopper
    networks:
      - elk-network
  postgres-itshopper:
    image: postgres:latest
    ports:
      - 5466:5432
    environment:
      - POSTGRES_DB=itshopper
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    networks:
      - elk-network
  redis-itshopper:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - elk-network
networks:
  elk-network:
    driver: bridge