on: 
  push:
    branches: ["main"]
jobs:
  checks-on-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependecies
      run: | 
        python -m pip install --upgrade pip
        pip install -f requirements.txt
    - name: Run tests
      run: python manage.py test
