on: 
  push:
    branches: ["main"]
jobs:
  checks-on-push:
    runs-on: ubuntu-latest
    services:
      postgres-itshopper:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: itshopper
          POSTGRES_USER": postgres
          POSTGRES_PASSWORD: postgres
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: python manage.py test
